kind: pipeline
name: drone
#workspace:
 # base: /build
  #path: worksapce
steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - /root/.m2
    volumes:
      - name: cache
        path: /cache

  - name: init
    image: maven:3-jdk-10
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true

  - name: build
    image: plugins/docker
    repo: test/test
    dockerfile: ./Dockerfile
    tags: latest

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - /root/.m2
    volumes:
      - name: cache
        path: /cache
