kind: pipeline
name: drone
steps:
  - name: init
    image: maven:3-jdk-10
    volumes:
     - name: cache
       path: /root/.m2
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
