version: "3"
networks:
  default:
    external:
      name: default-network
services:
  comapi:
    container_name: comapi
    image: swr.cn-north-1.myhuaweicloud.com/a82253452/comapi
    labels:
      - traefik.http.routers.comapi.rule=Host(`zhihuizhan.net`) && PathPrefix(`/api`)
      - traefik.http.routers.comapi.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/api
      - traefik.http.routers.comapi.middlewares=strip-prefix@docker
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /etc/localtime:/etc/localtime

