version: "3"
networks:
  default:
    external:
      name: default-network
services:
  comapi:
    container_name: drone-myapp
    image: swr.cn-north-1.myhuaweicloud.com/a82253452/comapi
    labels:
      - traefik.http.routers.myapp.rule=Host(`zhihuizhan.net`) && Path(`/api`)
      - traefik.http.routers.myapp.tls.certresolver=mytlschallenge
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /etc/localtime:/etc/localtime

