spring:
  mail:
    title: restapi线上环境告警
  datasource:
    url: jdbc:mysql://172.17.10.123:3306/kj?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: kanjian
    password: kanjian$$!@#
    initialSize: 10
    minIdle: 10
    maxActive: 2000
    maxWait: 60000
  redis:
    host: 123.57.249.102
    port: 6379
    password: zlsx8888.#@!
    database: 0
mybatis:
  type-aliases-package: com.zlsx.*.domain
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
jwt:
  key: 0e01234f23686b08abae11534a0ef1020e00568f23686b08abae11534a0ef809
  exp: 1
server:
  port: 8080
logging:
  file: run.log
cors:
  origins: '*'
swagger:
  enable: false
  basePath: restapi
push:
  prod_mode: true
url:
  dailyQuestion: https://apps.zhonglanmedia.com/kjwebapp/activity/community/topic.html
  videoTopic: https://apps.zhonglanmedia.com/kjwebapp/activity/appWebview/topic.html?videoid=
  selectedAlbumDetail: https://apps.zhonglanmedia.com/kjwebapp/activity/appShare/album/index.html?id=
  newUserTask: https://apps.zhonglanmedia.com/kjwebapp/activity/appWebview/novicesReward.html
  communityEntranceUrl:
    msgUrl: KJopenUrl://KJCommunityModule.login/KJMessagesClass
    rankUrl: https://apps.zhonglanmedia.com/kjwebapp/activity/community/rank.html?type=app&code=1
    historyUrl: KJopenUrl://KJCommunityModule/KJCommunityHistoryClass
    punchUrl: https://apps.zhonglanmedia.com/kjwebapp/activity/community/punch.html?type=app
  topic_url:
    h5TopicUrl: https://apps.zhonglanmedia.com/kjwebapp/activity/community/index.html?type=app&id={id}
    h5PkUrl: https://apps.zhonglanmedia.com/kjwebapp/activity/community/pk.html?type=app&id={id}
    h5QuestionUrl: https://apps.zhonglanmedia.com/kjwebapp/activity/community/question.html?type=app&id={id}
h5:
  url: https://apps.zhonglanmedia.com/kjwebapp/activity/appWebview/article.html?id=
enter_group:
  topic_id: 95
weapp:
  config:
    preAuthUrl: http://admin.wokanjian.com.cn/adminapi/notify/authorizerRefreshToken
  open:
    componentAppId: wxaef3251ba28a0c89
    componentSecret: 80176ce4cd1067e0c5f51c1c537d85df
    componentToken: token
    componentAesKey: r82FieYYZZ2tTG3Gklh9LBCh3k4Gxtwgsai4n2juvk1