version: "3"
networks:
  default:
    external:
      name: default-network
services:
  healthy:
    container_name: healthy
    image: yp/healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8008:8080
    volumes:
      - /etc/localtime:/etc/localtime